# Generated automatically from Makefile.in by configure.
# Generated automatically from Makefile.in by configure.

bindir = ${exec_prefix}/bin
datadir = ${prefix}/share
exec_prefix = ${prefix}
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr/local
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
top_srcdir = ../..
CFLAGS = -g -O2
CPPFLAGS = 
CXXFLAGS = 
DEFS = -DHAVE_CONFIG_H
LDFLAGS = 
LIBS = -lnsl 
CHMOD = chmod
DIRMOD = go+w

all:
	cd LISS; make all

clean: 
	rm -f *.o *.a core *~ \#*\#
	cd LISS; make clean

dist:	clean
	rm -f Makefile
	cd LISS; make dist

install:
	cd LISS; make install

uninstall:
	cd LISS; make uninstall


