# Generated automatically from Makefile.in by configure.
# Generated automatically from Makefile.in by configure.

bindir = ${exec_prefix}/bin
datadir = ${prefix}/share
exec_prefix = ${prefix}
includedir = ${prefix}/include
infodir = ${prefix}/info
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localstatedir = ${prefix}/var
mandir = ${prefix}/man
oldincludedir = /usr/include
prefix = /usr/local
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
top_srcdir = ../..
CFLAGS = -g -O2
CPPFLAGS = 
CXXFLAGS = 
DEFS = -DHAVE_CONFIG_H
LDFLAGS = 
LIBS = -lnsl 
CHMOD = chmod
DIRMOD = go+w

all:	
	cd dcc_time; make all
	cd dcc_misc; make all
	cd dcc_seed; make all
	cd steim123; make all

clean: 
	rm -f *.o *.a core *~ \#*\#
	cd dcc_time; make clean
	cd dcc_misc; make clean
	cd dcc_seed; make clean
	cd steim123; make clean

dist:	clean
	rm -f Makefile
	cd dcc_time; make dist
	cd dcc_misc; make dist
	cd dcc_seed; make dist
	cd steim123; make dist

install: 
	cd dcc_time; make install
	cd dcc_misc; make install
	cd dcc_seed; make install
	cd steim123; make install

uninstall: 
	cd dcc_time; make uninstall
	cd dcc_misc; make uninstall
	cd dcc_seed; make uninstall
	cd steim123; make uninstall

