.TH BDF 4 "16 September 1997"
.IX BDF
.SH NAME
BDF - ASL BDF (Big Data File) simple seismic work format
.SH DESCRIPTION
UNDER CONSTRUCTION
.SH EXAMPLES
.SH HISTORY
.SH "SEE ALSO"
.BR dumpseed(1) ,
.B SEED(4) 
.SH AUTHOR
Public Domain Software by Scott Halbert - Allied Signal Technical
Services Corporation under contract to the Albuquerque Seismological
Laboratory - United States Geological Survey - Department of Interior,
United States, North American Continent, Earth/Sol 3, Sagitarius Arm of
Milky Way Galaxy.
