.TH SEED 4 "16 September 1997"
.IX SEED
.SH NAME
SEED - Standard for the Exchange of Earthquake Data
.SH DESCRIPTION
UNDER CONSTRUCTION
.SH EXAMPLES
.SH HISTORY
.SH "SEE ALSO"
.B "SEED Reference Manual Version 2.3 - February 1993"
.br
.BR dumpseed(1) 
.SH AUTHOR
Public Domain Software by Scott Halbert - Allied Signal Technical
Services Corporation under contract to the Albuquerque Seismological
Laboratory - United States Geological Survey - Department of Interior,
United States, North American Continent, Earth/Sol 3, Sagitarius Arm of
Milky Way Galaxy.
