/* DCC Standard pool clasess */

#define NEWSTAGE_POOL "NEWSTAGE_POOL"
#define NEWSTAGE_ARCHIVE "NEWSTAGE_ARCHIVE"
#define NEWNET_POOL "NEWNET_POOL"
#define NEWVOL_POOL "NEWVOL_POOL"
#define OLDNET_POOL "OLDNET_POOL"
#define NET_ARCHIVE "NET_ARCHIVE"
#define NEWFOLDER_POOL "NEWFOLDER_POOL"
#define SBK_METRUM1 "SBK_METRUM"
#define SBK_METRUM2 "SBK_METRUMTMP"
#define NET_METRUM1 "NET_METRUM1"
#define NET_METRUM2 "NET_METRUM2"
